FROM python:3-alpine
RUN mkdir -p /usr/src/eitu
WORKDIR /usr/src/eitu
COPY requirements.txt /usr/src/eitu/
RUN pip install --no-cache-dir -r requirements.txt
COPY src /usr/src/eitu
CMD python -u main.py
