# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eitu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occupancy',
            old_name='occupancy',
            new_name='room_occupancy',
        ),
    ]
