# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-28 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eitu', '0003_auto_20161026_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEditEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('datetime_start', models.DateTimeField()),
                ('datetime_end', models.DateTimeField()),
                ('datetime_stamp', models.DateTimeField()),
                ('datetime_lastModified', models.DateTimeField()),
                ('summary', models.TextField()),
                ('rooms', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
