# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-31 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eitu', '0003_auto_20161026_1721'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Occupancy',
            new_name='wifi_occupancy',
        ),
    ]
