# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-28 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eitu', '0004_timeeditevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeeditevent',
            old_name='rooms',
            new_name='location',
        ),
    ]
