# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eitu', '0004_auto_20161031_1237'),
        ('eitu', '0005_auto_20161028_1024'),
    ]

    operations = [
    ]
