# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eitu', '0006_merge_20161103_1819'),
        ('eitu', '0006_merge_20161104_0702'),
    ]

    operations = [
    ]
